language: go
sudo: false

go:
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  include:
  - name: test coverage profile
    go: 1.11.x
    env: COVER="-bench=. -coverprofile=coverage.txt -covermode=atomic"

before_install:
  # don't use the miekg/dns when testing forks
  - mkdir -p $GOPATH/src/github.com/miekg
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/miekg/ || true

script:
  - go test -race -v "$COVER" ./...

after_success:
  - if [[ -n "${COVER}" ]]; then bash <(curl -s https://codecov.io/bash); fi
