language: go
sudo: false
go:
  - 1.5
  - 1.6
  - 1.7

before_install:
  - go get github.com/mattn/goveralls

  # don't use the miekg/dns when testing forks
  - mkdir -p $GOPATH/src/github.com/miekg
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/miekg/ || true

script:
  # run tests with coverage
  - goveralls -v
  # run benchmarks
  - go test -v -bench=. -run=^$
