language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  # don't use the miekg/dns when testing forks
  - mkdir -p $GOPATH/src/github.com/miekg
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/miekg/ || true

script:
  - go test -race -v -bench=.
