language: go
sudo: false
go:
  - 1.9.x
  - tip

env:
  - TESTS="-race -v -bench=. -coverprofile=coverage.txt -covermode=atomic"
  - TESTS="-race -v ./..."

addons:
  apt:
    packages:
      - unzip
      - build-essential

cache:
  directories:
    - $HOME/bind

before_install:
  # don't use the miekg/dns when testing forks
  - mkdir -p $GOPATH/src/github.com/miekg
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/miekg/ || true

install:
  - test -f $HOME/bind/sbin/named || $TRAVIS_BUILD_DIR/install-bind.bash $HOME/bind

script:
  - export PATH="$HOME/bind/sbin:$HOME/bind/bin:$PATH"
  - go test $TESTS

after_success:
  - bash <(curl -s https://codecov.io/bash)
