// *** DO NOT MODIFY ***
// AUTOGENERATED BY go generate from msg_generate.go

package dns

//import (
//"encoding/base64"
//"net"
//)

// pack*() functions

func (rr *A) pack(msg []byte, off int, compression map[string]int, compress bool) (int, error) {
	off, err := packHeader(rr.Hdr, msg, off, compression, compress)
	if err != nil {
		return off, err
	}
	off, err = packDataA(rr.A, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *AAAA) pack(msg []byte, off int, compression map[string]int, compress bool) (int, error) {
	off, err := packHeader(rr.Hdr, msg, off, compression, compress)
	if err != nil {
		return off, err
	}
	off, err = packDataAAAA(rr.AAAA, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *L32) pack(msg []byte, off int, compression map[string]int, compress bool) (int, error) {
	off, err := packHeader(rr.Hdr, msg, off, compression, compress)
	if err != nil {
		return off, err
	}
	off, err = packUint16(rr.Preference, msg, off, len(msg))
	if err != nil {
		return off, err
	}
	off, err = packDataA(rr.Locator32, msg, off)
	if err != nil {
		return off, err
	}
	return off, nil
}

func (rr *MX) pack(msg []byte, off int, compression map[string]int, compress bool) (int, error) {
	off, err := packHeader(rr.Hdr, msg, off, compression, compress)
	if err != nil {
		return off, err
	}
	off, err = packUint16(rr.Preference, msg, off, len(msg))
	if err != nil {
		return off, err
	}
	off, err = PackDomainName(rr.Mx, msg, off, compression, compress)
	if err != nil {
		return off, err
	}
	return off, nil
}

// unpack*() functions

func unpackA(msg []byte, off int) (*A, int, error) {
	if dynamicUpdate(off, len(msg)) {
		return nil, off, nil
	}
	var err error
	rr := new(A)
	rr.A, off, err = unpackDataA(msg, off)
	if err != nil {
		return rr, off, err
	}
	return rr, off, nil
}

func unpackAAAA(msg []byte, off int) (*AAAA, int, error) {
	if dynamicUpdate(off, len(msg)) {
		return nil, off, nil
	}
	var err error
	rr := new(AAAA)
	rr.AAAA, off, err = unpackDataAAAA(msg, off)
	if err != nil {
		return rr, off, err
	}
	return rr, off, nil
}

func unpackL32(msg []byte, off int) (*L32, int, error) {
	if dynamicUpdate(off, len(msg)) {
		return nil, off, nil
	}
	var err error
	rr := new(L32)
	rr.Preference, off, err = unpackUint16(msg, off, len(msg))
	if err != nil {
		return rr, off, err
	}
	rr.Locator32, off, err = unpackDataA(msg, off)
	if err != nil {
		return rr, off, err
	}
	return rr, off, nil
}

func unpackMX(msg []byte, off int) (*MX, int, error) {
	if dynamicUpdate(off, len(msg)) {
		return nil, off, nil
	}
	var err error
	rr := new(MX)
	rr.Preference, off, err = unpackUint16(msg, off, len(msg))
	if err != nil {
		return rr, off, err
	}
	rr.Mx, off, err = UnpackDomainName(msg, off)
	if err != nil {
		return rr, off, err
	}
	return rr, off, nil
}
