all: 
	gomake -C mx
	gomake -C q
	gomake -C chaos
	gomake -C dnssectest
	gomake -C axfr
	gomake -C zlutser

clean:
	gomake -C mx clean
	gomake -C q clean
	gomake -C chaos clean
	gomake -C dnssectest clean
	gomake -C axfr clean
	gomake -C zlutser clean
